[2023-10-02T02:39:42.204+0300] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_rf.task_get_data scheduled__2023-09-30T01:00:00+00:00 [queued]>
[2023-10-02T02:39:42.210+0300] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_rf.task_get_data scheduled__2023-09-30T01:00:00+00:00 [queued]>
[2023-10-02T02:39:42.210+0300] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-02T02:39:42.338+0300] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): task_get_data> on 2023-09-30 01:00:00+00:00
[2023-10-02T02:39:42.344+0300] {standard_task_runner.py:57} INFO - Started process 5216 to run task
[2023-10-02T02:39:42.353+0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_rf', 'task_get_data', 'scheduled__2023-09-30T01:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/test_dag_several_models.py', '--cfg-path', '/tmp/tmpnoxcwxys']
[2023-10-02T02:39:42.357+0300] {standard_task_runner.py:85} INFO - Job 58: Subtask task_get_data
[2023-10-02T02:39:42.443+0300] {task_command.py:415} INFO - Running <TaskInstance: train_rf.task_get_data scheduled__2023-09-30T01:00:00+00:00 [running]> on host dsbulgako1-QEMU-Virtual-Machine
[2023-10-02T02:39:42.543+0300] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='dmitrii.bulghakov@gmail.com' AIRFLOW_CTX_DAG_OWNER='Dmitry Bulgakov' AIRFLOW_CTX_DAG_ID='train_rf' AIRFLOW_CTX_TASK_ID='task_get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-30T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-30T01:00:00+00:00'
[2023-10-02T02:39:42.574+0300] {test_dag_several_models.py:59} INFO - Postgres connection initializing.
[2023-10-02T02:39:42.590+0300] {base.py:73} INFO - Using connection ID 'pg_connection' for task execution.
[2023-10-02T02:39:42.602+0300] {test_dag_several_models.py:64} INFO - Taking data from Postgres.
[2023-10-02T02:39:42.610+0300] {logging_mixin.py:151} WARNING - /home/dsbulgako1/my_repos/mlops_project/dags/test_dag_several_models.py:65 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2023-10-02T02:39:42.690+0300] {test_dag_several_models.py:67} INFO - S3 connection initializing.
[2023-10-02T02:39:42.702+0300] {base.py:73} INFO - Using connection ID 's3_connector' for task execution.
[2023-10-02T02:39:42.703+0300] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='s3_connector', conn_type='aws') credentials retrieved from login and password.
[2023-10-02T02:39:42.749+0300] {configprovider.py:949} INFO - Found endpoint for s3 via: config_global.
[2023-10-02T02:39:42.756+0300] {test_dag_several_models.py:72} INFO - S3 data uploading.
[2023-10-02T02:39:43.721+0300] {test_dag_several_models.py:75} INFO - Data uploading finished.
[2023-10-02T02:39:43.723+0300] {python.py:194} INFO - Done. Returned value was: {'model': 'rf', 'start_timestamp': '20231002 02:39', 'data_uploaded_timestamp': '20231002 02:39'}
[2023-10-02T02:39:43.754+0300] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=train_rf, task_id=task_get_data, execution_date=20230930T010000, start_date=20231001T233942, end_date=20231001T233943
[2023-10-02T02:39:43.800+0300] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-02T02:39:43.820+0300] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
