[2023-10-22T22:05:58.497+0300] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dm1trybu.get_data_from_postgres scheduled__2023-10-21T09:45:00+00:00 [queued]>
[2023-10-22T22:05:58.501+0300] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dm1trybu.get_data_from_postgres scheduled__2023-10-21T09:45:00+00:00 [queued]>
[2023-10-22T22:05:58.501+0300] {taskinstance.py:1359} INFO - Starting attempt 7 of 10
[2023-10-22T22:05:58.507+0300] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): get_data_from_postgres> on 2023-10-21 09:45:00+00:00
[2023-10-22T22:05:58.511+0300] {standard_task_runner.py:57} INFO - Started process 228096 to run task
[2023-10-22T22:05:58.514+0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dm1trybu', 'get_data_from_postgres', 'scheduled__2023-10-21T09:45:00+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/final_dag_3_models.py', '--cfg-path', '/tmp/tmpvf7in9c4']
[2023-10-22T22:05:58.516+0300] {standard_task_runner.py:85} INFO - Job 153: Subtask get_data_from_postgres
[2023-10-22T22:05:58.559+0300] {task_command.py:415} INFO - Running <TaskInstance: dm1trybu.get_data_from_postgres scheduled__2023-10-21T09:45:00+00:00 [running]> on host dsbulgako1-QEMU-Virtual-Machine
[2023-10-22T22:05:58.616+0300] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='dmitrii.bulghakov@bk.ru' AIRFLOW_CTX_DAG_OWNER='Dmitry Bulgakov' AIRFLOW_CTX_DAG_ID='dm1trybu' AIRFLOW_CTX_TASK_ID='get_data_from_postgres' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T09:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-21T09:45:00+00:00'
[2023-10-22T22:05:58.627+0300] {final_dag_3_models.py:116} INFO - Connecting to Postgres...
[2023-10-22T22:05:58.637+0300] {base.py:73} INFO - Using connection ID 'pg_connection' for task execution.
[2023-10-22T22:05:58.644+0300] {final_dag_3_models.py:121} INFO - Data downloading from Postgres...
[2023-10-22T22:05:58.645+0300] {logging_mixin.py:151} WARNING - /home/dsbulgako1/my_repos/mlops_project/dags/final_dag_3_models.py:122 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2023-10-22T22:05:58.704+0300] {final_dag_3_models.py:126} INFO - Connecting to S3...
[2023-10-22T22:05:58.712+0300] {base_aws.py:553} WARNING - Unable to find AWS Connection ID 's3_connection', switching to empty.
[2023-10-22T22:05:58.713+0300] {base_aws.py:161} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name='ru-central1'). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2023-10-22T22:05:58.733+0300] {credentials.py:1254} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2023-10-22T22:05:58.868+0300] {configprovider.py:949} INFO - Found endpoint for s3 via: config_global.
[2023-10-22T22:06:01.016+0300] {final_dag_3_models.py:132} INFO - Data is uploaded to S3.
[2023-10-22T22:06:01.018+0300] {python.py:194} INFO - Done. Returned value was: {'start_tiemstamp': '20231022 22:05', 'parent_run_name': 'parent_3_models', 'experiment_name': 'dm1trybu', 'experiment_id': '33', 'parent_run_id': '212ae9039a0b4dd8a51f6c3425799562', 'data_download_start': '20231022 22:05', 'data_download_end': '20231022 22:06'}
[2023-10-22T22:06:01.050+0300] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=dm1trybu, task_id=get_data_from_postgres, execution_date=20231021T094500, start_date=20231022T190558, end_date=20231022T190601
[2023-10-22T22:06:01.077+0300] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-22T22:06:01.095+0300] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
