[2023-10-22T21:15:59.678+0300] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dm1trybu.init scheduled__2023-10-21T09:45:00+00:00 [queued]>
[2023-10-22T21:15:59.682+0300] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dm1trybu.init scheduled__2023-10-21T09:45:00+00:00 [queued]>
[2023-10-22T21:15:59.682+0300] {taskinstance.py:1359} INFO - Starting attempt 20 of 20
[2023-10-22T21:15:59.690+0300] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): init> on 2023-10-21 09:45:00+00:00
[2023-10-22T21:15:59.694+0300] {standard_task_runner.py:57} INFO - Started process 218962 to run task
[2023-10-22T21:15:59.697+0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dm1trybu', 'init', 'scheduled__2023-10-21T09:45:00+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/final_dag_3_models.py', '--cfg-path', '/tmp/tmp5jnctmfh']
[2023-10-22T21:15:59.698+0300] {standard_task_runner.py:85} INFO - Job 136: Subtask init
[2023-10-22T21:15:59.742+0300] {task_command.py:415} INFO - Running <TaskInstance: dm1trybu.init scheduled__2023-10-21T09:45:00+00:00 [running]> on host dsbulgako1-QEMU-Virtual-Machine
[2023-10-22T21:15:59.802+0300] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='dmitrii.bulghakov@bk.ru' AIRFLOW_CTX_DAG_OWNER='Dmitry Bulgakov' AIRFLOW_CTX_DAG_ID='dm1trybu' AIRFLOW_CTX_TASK_ID='init' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T09:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='20' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-21T09:45:00+00:00'
[2023-10-22T21:15:59.802+0300] {final_dag_3_models.py:72} INFO - Initializing dag and collecting meta-data...
[2023-10-22T21:15:59.802+0300] {final_dag_3_models.py:82} INFO - Trying to set new experiment...
[2023-10-22T21:15:59.956+0300] {migration.py:213} INFO - Context impl PostgresqlImpl.
[2023-10-22T21:15:59.957+0300] {migration.py:216} INFO - Will assume transactional DDL.
[2023-10-22T21:15:59.972+0300] {final_dag_3_models.py:92} INFO - Experiment 'dm1trybu' already exists in MLFlow.
[2023-10-22T21:15:59.973+0300] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/dsbulgako1/my_repos/mlops_project/dags/final_dag_3_models.py", line 95, in init
    mlflow.set_experiment(metrics["experiment_name"])
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 148, in set_experiment
    raise MlflowException(
mlflow.exceptions.MlflowException: Cannot set a deleted experiment 'dm1trybu' as the active experiment. You can restore the experiment, or permanently delete the experiment to create a new one.
[2023-10-22T21:15:59.987+0300] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=dm1trybu, task_id=init, execution_date=20231021T094500, start_date=20231022T181559, end_date=20231022T181559
[2023-10-22T21:15:59.995+0300] {logging_mixin.py:151} WARNING - /home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-10-22T21:15:59.995+0300] {email.py:270} INFO - Email alerting: attempt 1
[2023-10-22T21:16:00.809+0300] {email.py:282} INFO - Sent an alert email to ['dmitrii.bulghakov@bk.ru']
[2023-10-22T21:16:01.803+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 136 for task init (Cannot set a deleted experiment 'dm1trybu' as the active experiment. You can restore the experiment, or permanently delete the experiment to create a new one.; 218962)
[2023-10-22T21:16:01.841+0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T21:16:01.859+0300] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
