[2023-10-22T20:33:39.074+0300] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dm1trybu.init scheduled__2023-10-21T09:45:00+00:00 [queued]>
[2023-10-22T20:33:39.078+0300] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dm1trybu.init scheduled__2023-10-21T09:45:00+00:00 [queued]>
[2023-10-22T20:33:39.078+0300] {taskinstance.py:1359} INFO - Starting attempt 8 of 8
[2023-10-22T20:33:39.084+0300] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): init> on 2023-10-21 09:45:00+00:00
[2023-10-22T20:33:39.089+0300] {standard_task_runner.py:57} INFO - Started process 209891 to run task
[2023-10-22T20:33:39.093+0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dm1trybu', 'init', 'scheduled__2023-10-21T09:45:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/final_dag_3_models.py', '--cfg-path', '/tmp/tmp283e3b4b']
[2023-10-22T20:33:39.096+0300] {standard_task_runner.py:85} INFO - Job 102: Subtask init
[2023-10-22T20:33:39.146+0300] {task_command.py:415} INFO - Running <TaskInstance: dm1trybu.init scheduled__2023-10-21T09:45:00+00:00 [running]> on host dsbulgako1-QEMU-Virtual-Machine
[2023-10-22T20:33:39.214+0300] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='dmitrii.bulghakov@bk.ru' AIRFLOW_CTX_DAG_OWNER='Dmitry Bulgakov' AIRFLOW_CTX_DAG_ID='dm1trybu' AIRFLOW_CTX_TASK_ID='init' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T09:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-21T09:45:00+00:00'
[2023-10-22T20:33:39.215+0300] {final_dag_3_models.py:72} INFO - Initializing dag and collecting meta-data...
[2023-10-22T20:33:39.215+0300] {final_dag_3_models.py:81} INFO - Trying to set new experiment...
[2023-10-22T20:33:39.455+0300] {migration.py:213} INFO - Context impl PostgresqlImpl.
[2023-10-22T20:33:39.456+0300] {migration.py:216} INFO - Will assume transactional DDL.
[2023-10-22T20:33:39.468+0300] {final_dag_3_models.py:89} INFO - Experiment 'dm1trybu' already exists in MLFlow.
[2023-10-22T20:33:39.468+0300] {final_dag_3_models.py:93} INFO - Creating parent run in MLFlow.
[2023-10-22T20:33:39.468+0300] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/dsbulgako1/my_repos/mlops_project/dags/final_dag_3_models.py", line 96, in init
    experiment_id=metrics["experiment_id"],
KeyError: 'experiment_id'
[2023-10-22T20:33:39.477+0300] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=dm1trybu, task_id=init, execution_date=20231021T094500, start_date=20231022T173339, end_date=20231022T173339
[2023-10-22T20:33:39.492+0300] {logging_mixin.py:151} WARNING - /home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-10-22T20:33:39.492+0300] {email.py:270} INFO - Email alerting: attempt 1
[2023-10-22T20:33:40.352+0300] {email.py:282} INFO - Sent an alert email to ['dmitrii.bulghakov@bk.ru']
[2023-10-22T20:33:41.508+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 102 for task init ('experiment_id'; 209891)
[2023-10-22T20:33:41.539+0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T20:33:41.558+0300] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
