[2023-09-28T01:40:45.164+0300] {processor.py:157} INFO - Started process (PID=12910) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:40:45.165+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:40:45.166+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:40:45.165+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:40:45.168+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:40:45.167+0300] {dagbag.py:347} ERROR - Failed to import: /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
Traceback (most recent call last):
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py", line 2, in <module>
    from dags_tasks_scripts import init
ModuleNotFoundError: No module named 'dags_tasks_scripts'
[2023-09-28T01:40:45.168+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:40:45.191+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.029 seconds
[2023-09-28T01:41:15.313+0300] {processor.py:157} INFO - Started process (PID=13005) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:41:15.315+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:41:15.315+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:41:15.315+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:41:15.317+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:41:15.317+0300] {dagbag.py:347} ERROR - Failed to import: /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
Traceback (most recent call last):
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py", line 2, in <module>
    from dags_tasks_scripts import init
ModuleNotFoundError: No module named 'dags_tasks_scripts'
[2023-09-28T01:41:15.317+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:41:15.339+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.028 seconds
[2023-09-28T01:41:45.453+0300] {processor.py:157} INFO - Started process (PID=13015) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:41:45.454+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:41:45.455+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:41:45.454+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:41:45.456+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:41:45.456+0300] {dagbag.py:347} ERROR - Failed to import: /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
Traceback (most recent call last):
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py", line 2, in <module>
    from dags_tasks_scripts import init
ModuleNotFoundError: No module named 'dags_tasks_scripts'
[2023-09-28T01:41:45.456+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:41:45.479+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.027 seconds
[2023-09-28T01:42:15.660+0300] {processor.py:157} INFO - Started process (PID=13027) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:42:15.662+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:42:15.662+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:42:15.662+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:42:15.666+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:42:15.665+0300] {dagbag.py:347} ERROR - Failed to import: /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
Traceback (most recent call last):
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py", line 2, in <module>
    from dags_tasks_scripts import init
ModuleNotFoundError: No module named 'dags_tasks_scripts'
[2023-09-28T01:42:15.666+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:42:15.696+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.040 seconds
[2023-09-28T01:42:45.994+0300] {processor.py:157} INFO - Started process (PID=13034) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:42:45.995+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:42:45.996+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:42:45.996+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:42:46.001+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:42:46.000+0300] {dagbag.py:347} ERROR - Failed to import: /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
Traceback (most recent call last):
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py", line 2, in <module>
    from dags_tasks_scripts import init
ModuleNotFoundError: No module named 'dags_tasks_scripts'
[2023-09-28T01:42:46.001+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:42:46.030+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.040 seconds
[2023-09-28T01:43:16.271+0300] {processor.py:157} INFO - Started process (PID=13041) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:43:16.272+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:43:16.273+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:43:16.273+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:43:16.277+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:43:16.275+0300] {dagbag.py:347} ERROR - Failed to import: /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
Traceback (most recent call last):
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py", line 2, in <module>
    from dags_tasks_scripts import init
ModuleNotFoundError: No module named 'dags_tasks_scripts'
[2023-09-28T01:43:16.277+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:43:16.308+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.041 seconds
[2023-09-28T01:43:46.568+0300] {processor.py:157} INFO - Started process (PID=13052) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:43:46.570+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:43:46.570+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:43:46.570+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:43:46.574+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:43:46.573+0300] {dagbag.py:347} ERROR - Failed to import: /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
Traceback (most recent call last):
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py", line 2, in <module>
    from dags_tasks_scripts import init
ModuleNotFoundError: No module named 'dags_tasks_scripts'
[2023-09-28T01:43:46.574+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:43:46.605+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.040 seconds
[2023-09-28T01:44:16.738+0300] {processor.py:157} INFO - Started process (PID=13069) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:44:16.739+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:44:16.739+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:44:16.739+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:44:16.741+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:44:16.741+0300] {dagbag.py:347} ERROR - Failed to import: /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
Traceback (most recent call last):
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py", line 2, in <module>
    from dags_tasks_scripts import init
ModuleNotFoundError: No module named 'dags_tasks_scripts'
[2023-09-28T01:44:16.742+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:44:16.764+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.029 seconds
[2023-09-28T01:44:46.943+0300] {processor.py:157} INFO - Started process (PID=13081) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:44:46.944+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:44:46.946+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:44:46.945+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:44:46.951+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:44:46.949+0300] {dagbag.py:347} ERROR - Failed to import: /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
Traceback (most recent call last):
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py", line 2, in <module>
    from dags_tasks_scripts import init
ModuleNotFoundError: No module named 'dags_tasks_scripts'
[2023-09-28T01:44:46.951+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:44:46.985+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.055 seconds
[2023-09-28T01:45:01.027+0300] {processor.py:157} INFO - Started process (PID=13091) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:45:01.028+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:45:01.028+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:45:01.028+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:45:01.031+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:45:01.030+0300] {dagbag.py:347} ERROR - Failed to import: /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
Traceback (most recent call last):
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py", line 2, in <module>
    from dags_tasks_scripts.init import main
ModuleNotFoundError: No module named 'dags_tasks_scripts'
[2023-09-28T01:45:01.031+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:45:01.054+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.030 seconds
[2023-09-28T01:45:31.227+0300] {processor.py:157} INFO - Started process (PID=13157) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:45:31.228+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:45:31.228+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:45:31.228+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:45:31.232+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:45:31.231+0300] {dagbag.py:347} ERROR - Failed to import: /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
Traceback (most recent call last):
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py", line 2, in <module>
    from dags_tasks_scripts.init import main
ModuleNotFoundError: No module named 'dags_tasks_scripts'
[2023-09-28T01:45:31.232+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:45:31.260+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.036 seconds
[2023-09-28T01:46:01.442+0300] {processor.py:157} INFO - Started process (PID=13221) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:46:01.445+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:46:01.446+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:46:01.445+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:46:01.463+0300] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag_mlops']) retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:46:01.548+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:46:01.548+0300] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:test_dag_mlops' as access control is unset.
[2023-09-28T01:46:01.548+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:46:01.548+0300] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-28T01:46:01.561+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:46:01.560+0300] {dag.py:3696} INFO - Setting next_dagrun for test_dag_mlops to 2023-09-27T01:00:00+00:00, run_after=2023-09-28T01:00:00+00:00
[2023-09-28T01:46:01.572+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.134 seconds
[2023-09-28T01:46:07.481+0300] {processor.py:157} INFO - Started process (PID=13252) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:46:07.483+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:46:07.484+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:46:07.483+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:46:07.486+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:46:07.485+0300] {dagbag.py:347} ERROR - Failed to import: /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
Traceback (most recent call last):
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py", line 2, in <module>
    from airflow.dags.dags_tasks_scripts.init import main
ModuleNotFoundError: No module named 'airflow.dags'
[2023-09-28T01:46:07.486+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:46:07.508+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.029 seconds
[2023-09-28T01:46:37.658+0300] {processor.py:157} INFO - Started process (PID=13263) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:46:37.658+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:46:37.659+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:46:37.659+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:46:37.660+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:46:37.660+0300] {dagbag.py:347} ERROR - Failed to import: /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
Traceback (most recent call last):
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py", line 2, in <module>
    from airflow.dags.dags_tasks_scripts.init import main
ModuleNotFoundError: No module named 'airflow.dags'
[2023-09-28T01:46:37.660+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:46:37.680+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.025 seconds
[2023-09-28T01:47:07.845+0300] {processor.py:157} INFO - Started process (PID=13275) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:47:07.847+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:47:07.847+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:47:07.847+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:47:07.849+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:47:07.849+0300] {dagbag.py:347} ERROR - Failed to import: /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
Traceback (most recent call last):
  File "/home/dsbulgako1/my_repos/mlops_project/env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py", line 2, in <module>
    from airflow.dags.dags_tasks_scripts.init import main
ModuleNotFoundError: No module named 'airflow.dags'
[2023-09-28T01:47:07.850+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:47:07.875+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.033 seconds
[2023-09-28T01:47:23.939+0300] {processor.py:157} INFO - Started process (PID=13305) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:47:23.940+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:47:23.940+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:47:23.940+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:47:23.948+0300] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag_mlops']) retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:47:23.974+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:47:23.974+0300] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-28T01:47:23.986+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:47:23.986+0300] {dag.py:3696} INFO - Setting next_dagrun for test_dag_mlops to 2023-09-27T01:00:00+00:00, run_after=2023-09-28T01:00:00+00:00
[2023-09-28T01:47:23.996+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.060 seconds
[2023-09-28T01:47:54.120+0300] {processor.py:157} INFO - Started process (PID=13348) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:47:54.120+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:47:54.121+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:47:54.120+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:47:54.128+0300] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag_mlops']) retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:47:54.151+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:47:54.151+0300] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-28T01:47:54.161+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:47:54.161+0300] {dag.py:3696} INFO - Setting next_dagrun for test_dag_mlops to 2023-09-27T01:00:00+00:00, run_after=2023-09-28T01:00:00+00:00
[2023-09-28T01:47:54.168+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.051 seconds
[2023-09-28T01:48:24.222+0300] {processor.py:157} INFO - Started process (PID=13376) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:48:24.223+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:48:24.223+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:48:24.223+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:48:24.231+0300] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag_mlops']) retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:48:24.255+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:48:24.255+0300] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-28T01:48:24.267+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:48:24.267+0300] {dag.py:3696} INFO - Setting next_dagrun for test_dag_mlops to 2023-09-27T01:00:00+00:00, run_after=2023-09-28T01:00:00+00:00
[2023-09-28T01:48:24.276+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.057 seconds
[2023-09-28T01:48:54.423+0300] {processor.py:157} INFO - Started process (PID=13455) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:48:54.424+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:48:54.424+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:48:54.424+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:48:54.432+0300] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag_mlops']) retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:48:54.458+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:48:54.457+0300] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-28T01:48:54.468+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:48:54.468+0300] {dag.py:3696} INFO - Setting next_dagrun for test_dag_mlops to 2023-09-27T01:00:00+00:00, run_after=2023-09-28T01:00:00+00:00
[2023-09-28T01:48:54.477+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.057 seconds
[2023-09-28T01:49:24.601+0300] {processor.py:157} INFO - Started process (PID=13517) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:49:24.602+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:49:24.603+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:49:24.602+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:49:24.610+0300] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag_mlops']) retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:49:24.634+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:49:24.634+0300] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-28T01:49:24.646+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:49:24.646+0300] {dag.py:3696} INFO - Setting next_dagrun for test_dag_mlops to 2023-09-27T01:00:00+00:00, run_after=2023-09-28T01:00:00+00:00
[2023-09-28T01:49:24.657+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.058 seconds
[2023-09-28T01:49:54.729+0300] {processor.py:157} INFO - Started process (PID=13524) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:49:54.730+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:49:54.731+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:49:54.731+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:49:54.746+0300] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag_mlops']) retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:49:54.791+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:49:54.791+0300] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-28T01:49:54.807+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:49:54.807+0300] {dag.py:3696} INFO - Setting next_dagrun for test_dag_mlops to 2023-09-27T01:00:00+00:00, run_after=2023-09-28T01:00:00+00:00
[2023-09-28T01:49:54.817+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.093 seconds
[2023-09-28T01:50:24.871+0300] {processor.py:157} INFO - Started process (PID=13577) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:50:24.872+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:50:24.873+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:50:24.873+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:50:24.887+0300] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag_mlops']) retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:50:24.921+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:50:24.921+0300] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-28T01:50:24.935+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:50:24.934+0300] {dag.py:3696} INFO - Setting next_dagrun for test_dag_mlops to 2023-09-27T01:00:00+00:00, run_after=2023-09-28T01:00:00+00:00
[2023-09-28T01:50:24.943+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.076 seconds
[2023-09-28T01:50:49.037+0300] {processor.py:157} INFO - Started process (PID=13588) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:50:49.038+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:50:49.039+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:50:49.039+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:50:49.050+0300] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag_mlops']) retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:50:49.082+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:50:49.082+0300] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-28T01:50:49.095+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:50:49.095+0300] {dag.py:3696} INFO - Setting next_dagrun for test_dag_mlops to 2023-09-27T01:00:00+00:00, run_after=2023-09-28T01:00:00+00:00
[2023-09-28T01:50:49.115+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.081 seconds
[2023-09-28T01:51:19.165+0300] {processor.py:157} INFO - Started process (PID=13631) to work on /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:51:19.167+0300] {processor.py:829} INFO - Processing file /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py for tasks to queue
[2023-09-28T01:51:19.168+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:51:19.168+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:51:19.179+0300] {processor.py:839} INFO - DAG(s) dict_keys(['test_dag_mlops']) retrieved from /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py
[2023-09-28T01:51:19.215+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:51:19.215+0300] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-28T01:51:19.228+0300] {logging_mixin.py:151} INFO - [2023-09-28T01:51:19.228+0300] {dag.py:3696} INFO - Setting next_dagrun for test_dag_mlops to 2023-09-27T01:00:00+00:00, run_after=2023-09-28T01:00:00+00:00
[2023-09-28T01:51:19.240+0300] {processor.py:179} INFO - Processing /home/dsbulgako1/my_repos/mlops_project/airflow/dags/test_dag_mlops.py took 0.077 seconds
